### ISSUE TITLE
Export error for 2 models

### ISSUE THREAD

**Issue by Aetherium1947** [smlu/blender-ijim#1]
Hello Smlu, I send you a private message in GOG.com concerning Indy modding (HD 3do files) and .CND to .NDY conversion... But I'm here to report a bug, when I try to export "gen_ij.3do" and "gen_im.3do" (even if I don't modify the file). The error message is in the picture:

![exportbug](https://user-images.githubusercontent.com/66077892/83162417-042ca100-a10a-11ea-8199-f5a8b6e135b2.png)

It's the same error for Indy in the minecar (gen_im.3do) but It work good for all others models.

Thanks for all your tools! (Sorry for my language: I'm french)

**Comment by smlu** [comment]
Hey @Aetherium1947, thank you for reporting this bug. I'll look into it.

**Comment by smlu** [comment]
@Aetherium1947 the [develop](https://github.com/smlu/blender-ijim/tree/develop) branch has fix for this issue, if you want to test it before I merge it into master.

**Comment by Aetherium1947** [comment]
I did not understand how to generate a .SLN file for visual studio with
cmake -DCMAKE_BUILD_TYPE=Release ..

I'm lost

But I trust you on this modification.

**Comment by smlu** [comment]
No compiling is needed for this. 

You just `download or clone` [develop](https://github.com/smlu/blender-ijim/tree/develop) branch. Then extract `ijim` folder to `scripts\addons` folder and replace existing folder there.  On windows the `scripts\addons` folder can be found in `%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\2.79\`. For other platforms see [here](https://docs.blender.org/manual/en/2.79/getting_started/installing/configuration/directories.html).
After that restart blender (or press `F8` to reload scripts in blender).

The other option is to zip th `ijim` folder and then import it in Blender.

**Comment by Aetherium1947** [comment]
Thanks, it works and I don't have problem in game!

**Comment by smlu** [comment]
Great, then I'll merge develop branch into master.
