### ISSUE TITLE
Trying to enabling addon in last 2.79 release gives errors.

### ISSUE THREAD

**Issue by eGax** [smlu/blender-ijim#3]
The add-on installs fine in the blender version 2.79 listed under requirements, but when trying to enable it in the Blender User Add-ons Preferences it throws up an error message and doesn't enable it.
![image](https://user-images.githubusercontent.com/9817245/155880350-082267f6-fb65-4d69-8f35-08ff5fa484ec.png)

```
Traceback (most recent call last):
  File "/var/lib/snapd/snap/blender/20/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/retro/.config/blender/2.79/scripts/addons/ijim/__init__.py", line 50, in <module>
    import ijim.model.model3doExporter as model3doExporter
  File "/home/retro/.config/blender/2.79/scripts/addons/ijim/model/model3doExporter.py", line 13, in <module>
    from .model3do import *
  File "/home/retro/.config/blender/2.79/scripts/addons/ijim/model/model3do.py", line 61
    self.material_idx: int      = -1
                     ^
SyntaxError: invalid syntax
```

![image](https://user-images.githubusercontent.com/9817245/155880365-3d6429a2-ade8-4b20-bd2e-3fdac83f5ab8.png)
How are other people getting this enabled to use it?

**Comment by smlu** [comment]
Hey, thank you for reporting the issue.

First thing to do is to check which version of python your blender installation uses. Python 3.6 is required for the addon to work. I'm guessing that blender in your case uses the python version 3.5.x. 
If you have a separate installation of python on your system check that it is not in conflict with blender.
Another option is to try to install other version of blender 2.9 from here: [https://download.blender.org/release/Blender2.79/](https://download.blender.org/release/Blender2.79/)
Some additional info on blender 2.79 and python versions: [https://developer.blender.org/T54355](https://developer.blender.org/T54355)

**Comment by eGax** [comment]
Ah OK, yeah my system installed python is 3.10.2 (`Python 3.10.2 (main, Jan 15 2022, 19:56:27). I guess it is too new for the addon to work.

**Comment by eGax** [comment]
I was able to install and enable the addon in blender versions 2.8 and higher, but it doesn't appear in the import or export list.
![image](https://user-images.githubusercontent.com/9817245/156112698-16c47b7c-1171-48da-8773-91f1c424e4b5.png)
Strangely enough the addon tells me `Upgrade to 2.8x required` even when using any of the 2.8.x releases. Anyway I went through all the blender 2.78 to 2.8.x versions and the addon doesn't work in Linux or even in a windows VM with the last version of python 3.6.x released. Either it won't enable in versions 2.79b and lower, or can be enabled in 2.80 and greater, but doesn't appear in the import/export menus.

**Comment by smlu** [comment]
In blender v2.8+ they introduced breaking changes and I haven't manage to upgrade this addon yet. The only version that it should work now is 2.79.

Ok, another thing to check is the version of python used in blender. To do this open python console in blender and check that it states version at least 3.6: 
![img](https://user-images.githubusercontent.com/4377556/156157589-03ed9799-b5b2-413c-a4de-a006710ad7ca.png)
(WIn64 zip Blender 2.79 hash: e045fe53f1b0 date: 2019-06-27 10:41)

Fyi, the syntax error you're getting is probably due missing [PEP 526](https://www.python.org/dev/peps/pep-0526/) which should be available from python 3.6 onward.

**Comment by eGax** [comment]
Thanks again for the patience and info.

All the 2.79 versions available from https://download.blender.org/release/Blender2.79/ have the same python version:
`PYTHON INTERACTIVE CONSOLE 3.5.3 (default, May 20 2017, 19:10:40) [MSC v.1800 64 bit (AMD64)]`

![Screenshot_20220301_165149](https://user-images.githubusercontent.com/9817245/156255617-f0316ff7-7c97-40cb-977d-6504f25794ce.png)

Even with python 3.6.x or greater installed in system in either Windows or Linux the python console in blender 2.79 reports using the internal version 3.5.3.

How can I replace the blender included 3.5.3 python version or make blender use the system installed 3.6.x+ or greater and not the included 3.5? The answer to that should fix my issues.

**Comment by smlu** [comment]
Can you try the latest build of blender 2.79: [https://download.blender.org/release/Blender2.79/latest/](https://download.blender.org/release/Blender2.79/latest/).
I've checked the win64 and 64 bit version for Linux and both have python 3.7.

**Comment by eGax** [comment]
WOW, I had thought I already tried those versions. Everything is good now. Thank you so much for the assistance.
